// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Times                int32                    `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
	Pair                 []*StringInt32NumberPair `protobuf:"bytes,2,rep,name=pair,proto3" json:"pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *Message) GetPair() []*StringInt32NumberPair {
	if m != nil {
		return m.Pair
	}
	return nil
}

type StringInt32NumberPair struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Int32Number          int32    `protobuf:"varint,2,opt,name=int32Number,proto3" json:"int32Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringInt32NumberPair) Reset()         { *m = StringInt32NumberPair{} }
func (m *StringInt32NumberPair) String() string { return proto.CompactTextString(m) }
func (*StringInt32NumberPair) ProtoMessage()    {}
func (*StringInt32NumberPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *StringInt32NumberPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringInt32NumberPair.Unmarshal(m, b)
}
func (m *StringInt32NumberPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringInt32NumberPair.Marshal(b, m, deterministic)
}
func (m *StringInt32NumberPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringInt32NumberPair.Merge(m, src)
}
func (m *StringInt32NumberPair) XXX_Size() int {
	return xxx_messageInfo_StringInt32NumberPair.Size(m)
}
func (m *StringInt32NumberPair) XXX_DiscardUnknown() {
	xxx_messageInfo_StringInt32NumberPair.DiscardUnknown(m)
}

var xxx_messageInfo_StringInt32NumberPair proto.InternalMessageInfo

func (m *StringInt32NumberPair) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *StringInt32NumberPair) GetInt32Number() int32 {
	if m != nil {
		return m.Int32Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*StringInt32NumberPair)(nil), "message.StringInt32NumberPair")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x82, 0xb9,
	0xd8, 0x7d, 0x21, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0xdc, 0xd4, 0x62, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0xc8, 0x88, 0x8b, 0xa5, 0x20, 0x31, 0xb3, 0x48, 0x82, 0x49,
	0x81, 0x59, 0x83, 0xdb, 0x48, 0x4e, 0x0f, 0x66, 0x4e, 0x70, 0x49, 0x51, 0x66, 0x5e, 0xba, 0x67,
	0x5e, 0x89, 0xb1, 0x91, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x51, 0x40, 0x62, 0x66, 0x51, 0x10, 0x58,
	0xad, 0x92, 0x37, 0x97, 0x28, 0x56, 0x69, 0x21, 0x01, 0x2e, 0xe6, 0xe2, 0x92, 0x22, 0xb0, 0x05,
	0x9c, 0x41, 0x20, 0xa6, 0x90, 0x02, 0x17, 0x77, 0x26, 0x42, 0x91, 0x04, 0x13, 0xd8, 0x6a, 0x64,
	0xa1, 0x24, 0x36, 0xb0, 0x8b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xa8, 0x66, 0x83,
	0xc2, 0x00, 0x00, 0x00,
}
